[workspace]
name = "boris-clip"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.10"
ffmpeg = "*"
pandas = ">=1.5"
click = ">=8.0"
pip = "*"

[feature.dev.dependencies]
pytest = "*"
pytest-cov = "*"
zensical = ">=0.0.23,<0.0.24"
mkdocstrings = ">=1.0.3,<2"
mkdocstrings-python = ">=2.0.2,<3"

[environments]
dev = ["dev"]

[feature.dev.tasks]
install = "pip install -e . --no-deps"
test = { cmd = "pytest tests/", depends-on = ["install"] }
clip = { cmd = "boris-clip", depends-on = ["install"] }
